#!/usr/bin/env bash
# openclaw-local-caddy-setup.sh
# Sets up a local Caddy TLS reverse proxy in front of an OpenClaw gateway.
# Encrypts all C2 traffic on the LAN — gateway stays on loopback only.
#
# Usage: ./openclaw-local-caddy-setup.sh [hostname] [gateway-port] [tls-port]
#   hostname:     SNI hostname for the TLS cert (default: $(hostname).local)
#   gateway-port: OpenClaw gateway port (default: 18789)
#   tls-port:     Caddy TLS listen port (default: 9443)
#
# What it does:
#   1. Installs Caddy if missing (brew on macOS, apt on Linux)
#   2. Writes a Caddyfile that proxies https://<hostname>:<tls-port> → http://localhost:<gw-port>
#   3. Creates a launchd plist (macOS) or systemd unit (Linux) for auto-start
#   4. Starts the service
#   5. Trusts the internal CA (macOS only, requires sudo)
#
# Prerequisites:
#   - OpenClaw gateway running on loopback (gateway.bind = "loopback")
#   - brew (macOS) or apt (Linux)

set -euo pipefail

BOLD='\033[1m'
DIM='\033[2m'
CYAN='\033[36m'
GREEN='\033[32m'
YELLOW='\033[33m'
RED='\033[31m'
RESET='\033[0m'

HOSTNAME="${1:-$(hostname).local}"
GW_PORT="${2:-18789}"
TLS_PORT="${3:-9443}"

OS="$(uname -s)"
CADDY_DIR="$HOME/.openclaw/caddy"

echo -e "${CYAN}${BOLD}═══════════════════════════════════════════${RESET}"
echo -e "${CYAN}${BOLD}  OpenClaw Gateway — Local TLS Setup${RESET}"
echo -e "${CYAN}${BOLD}═══════════════════════════════════════════${RESET}"
echo
echo -e "  Hostname:     ${BOLD}${HOSTNAME}${RESET}"
echo -e "  Gateway:      ${BOLD}http://localhost:${GW_PORT}${RESET}"
echo -e "  TLS endpoint: ${BOLD}https://${HOSTNAME}:${TLS_PORT}${RESET}"
echo

# ─── Step 1: Install Caddy ──────────────────────────────────────
echo -e "${BOLD}[1/5] Checking Caddy...${RESET}"
if command -v caddy &>/dev/null; then
    echo -e "  ${GREEN}✓${RESET} Caddy $(caddy version 2>/dev/null | head -1) already installed"
else
    echo -e "  Installing Caddy..."
    case "$OS" in
        Darwin)
            brew install caddy
            ;;
        Linux)
            if command -v apt-get &>/dev/null; then
                sudo apt-get install -y debian-keyring debian-archive-keyring apt-transport-https
                curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
                curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
                sudo apt-get update
                sudo apt-get install -y caddy
            else
                echo -e "  ${RED}✗${RESET} Unsupported package manager. Install Caddy manually: https://caddyserver.com/docs/install"
                exit 1
            fi
            ;;
        *)
            echo -e "  ${RED}✗${RESET} Unsupported OS: $OS"
            exit 1
            ;;
    esac
    echo -e "  ${GREEN}✓${RESET} Caddy installed"
fi

# ─── Step 2: Verify gateway is running ──────────────────────────
echo -e "${BOLD}[2/5] Checking gateway on localhost:${GW_PORT}...${RESET}"
if curl -s -o /dev/null -w "%{http_code}" "http://localhost:${GW_PORT}/" 2>/dev/null | grep -q "200\|404\|401"; then
    echo -e "  ${GREEN}✓${RESET} Gateway is responding"
else
    echo -e "  ${YELLOW}⚠${RESET} Gateway not responding on localhost:${GW_PORT}"
    echo -e "  ${DIM}Make sure gateway.bind is set to \"loopback\" in openclaw.json${RESET}"
    echo -e "  ${DIM}Continuing anyway (Caddy will retry connections)...${RESET}"
fi

# ─── Step 3: Write Caddyfile ────────────────────────────────────
echo -e "${BOLD}[3/5] Writing Caddyfile...${RESET}"
mkdir -p "$CADDY_DIR"

cat > "$CADDY_DIR/Caddyfile" << EOF
# OpenClaw Gateway — Local TLS Reverse Proxy
# Generated by openclaw-local-caddy-setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Encrypts C2 traffic on the LAN, proxies to loopback gateway.

${HOSTNAME}:${TLS_PORT} {
	tls internal
	reverse_proxy http://localhost:${GW_PORT}
}
EOF

caddy fmt --overwrite "$CADDY_DIR/Caddyfile" 2>/dev/null || true
echo -e "  ${GREEN}✓${RESET} Caddyfile written to ${DIM}${CADDY_DIR}/Caddyfile${RESET}"

# ─── Step 4: Create service ─────────────────────────────────────
echo -e "${BOLD}[4/5] Creating service...${RESET}"

CADDY_BIN="$(command -v caddy)"

case "$OS" in
    Darwin)
        PLIST="$HOME/Library/LaunchAgents/com.openclaw.caddy.plist"
        cat > "$PLIST" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.openclaw.caddy</string>
    <key>ProgramArguments</key>
    <array>
        <string>${CADDY_BIN}</string>
        <string>run</string>
        <string>--config</string>
        <string>${CADDY_DIR}/Caddyfile</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${CADDY_DIR}/caddy.stdout.log</string>
    <key>StandardErrorPath</key>
    <string>${CADDY_DIR}/caddy.stderr.log</string>
</dict>
</plist>
EOF
        # Stop existing if running
        launchctl unload "$PLIST" 2>/dev/null || true
        launchctl load "$PLIST"
        echo -e "  ${GREEN}✓${RESET} LaunchAgent created and loaded"
        echo -e "  ${DIM}${PLIST}${RESET}"
        ;;
    Linux)
        UNIT="/etc/systemd/system/openclaw-caddy.service"
        sudo tee "$UNIT" > /dev/null << EOF
[Unit]
Description=OpenClaw Caddy TLS Proxy
After=network.target

[Service]
Type=simple
User=$(whoami)
ExecStart=${CADDY_BIN} run --config ${CADDY_DIR}/Caddyfile
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
        sudo systemctl daemon-reload
        sudo systemctl enable --now openclaw-caddy
        echo -e "  ${GREEN}✓${RESET} systemd service created and started"
        echo -e "  ${DIM}${UNIT}${RESET}"
        ;;
esac

# Wait for Caddy to start
sleep 3

# ─── Step 5: Trust CA + verify ──────────────────────────────────
echo -e "${BOLD}[5/5] Verifying TLS...${RESET}"

case "$OS" in
    Darwin)
        CA_ROOT="$HOME/Library/Application Support/Caddy/pki/authorities/local/root.crt"
        if [ -f "$CA_ROOT" ]; then
            echo -e "  ${YELLOW}Trusting Caddy internal CA (may prompt for password)...${RESET}"
            sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$CA_ROOT" 2>/dev/null && \
                echo -e "  ${GREEN}✓${RESET} CA trusted in system keychain" || \
                echo -e "  ${YELLOW}⚠${RESET} Could not auto-trust CA. Run manually:\n    sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain \"${CA_ROOT}\""
        else
            echo -e "  ${YELLOW}⚠${RESET} CA root cert not found yet (Caddy may still be generating it)"
        fi
        ;;
    Linux)
        CA_ROOT="$HOME/.local/share/caddy/pki/authorities/local/root.crt"
        if [ -f "$CA_ROOT" ]; then
            sudo cp "$CA_ROOT" /usr/local/share/ca-certificates/caddy-local.crt
            sudo update-ca-certificates 2>/dev/null && \
                echo -e "  ${GREEN}✓${RESET} CA trusted" || \
                echo -e "  ${YELLOW}⚠${RESET} Could not auto-trust CA"
        fi
        ;;
esac

# Test the connection
echo
if curl -sk -o /dev/null -w "%{http_code}" "https://localhost:${TLS_PORT}/" 2>/dev/null | grep -q "200\|404\|401"; then
    echo -e "  ${GREEN}${BOLD}✅ TLS proxy is live!${RESET}"
else
    echo -e "  ${YELLOW}⚠${RESET} TLS proxy not responding yet on localhost:${TLS_PORT}"
    echo -e "  ${DIM}Check logs: cat ${CADDY_DIR}/caddy.stderr.log${RESET}"
fi

# Test from LAN IP
LAN_IP=$(ifconfig 2>/dev/null | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}' || hostname -I 2>/dev/null | awk '{print $1}')
if [ -n "$LAN_IP" ]; then
    if curl -sk -o /dev/null -w "%{http_code}" "https://${LAN_IP}:${TLS_PORT}/" 2>/dev/null | grep -q "200\|404\|401"; then
        echo -e "  ${GREEN}${BOLD}✅ LAN accessible at https://${LAN_IP}:${TLS_PORT}${RESET}"
    else
        echo -e "  ${DIM}LAN test (${LAN_IP}:${TLS_PORT}) — may need SNI: use https://${HOSTNAME}:${TLS_PORT}${RESET}"
    fi
fi

echo
echo -e "${GREEN}${BOLD}Setup complete!${RESET}"
echo
echo -e "  ${BOLD}Encrypted endpoint:${RESET} https://${HOSTNAME}:${TLS_PORT}"
echo -e "  ${BOLD}Caddyfile:${RESET}          ${CADDY_DIR}/Caddyfile"
echo -e "  ${BOLD}Logs:${RESET}               ${CADDY_DIR}/caddy.stderr.log"
echo
echo -e "  ${BOLD}Test:${RESET}"
echo -e "  openssl s_client -connect ${LAN_IP:-<LAN_IP>}:${TLS_PORT} -servername ${HOSTNAME} < /dev/null | openssl x509 -text"
echo
echo -e "  ${BOLD}OpenClaw config (optional, for remote nodes):${RESET}"
echo -e "  gateway.remote.url = \"wss://${HOSTNAME}:${TLS_PORT}\""
